### Import basic libraries

In [1]:
import pandas as pd
import numpy as np

In [120]:
df=pd.read_csv('train_qWM28Yl.csv')

In [3]:
df.shape

(58592, 44)

In [4]:
df.head()

policy_id  policy_tenure  age_of_car  age_of_policyholder area_cluster  \
0   ID00001       0.515874        0.05             0.644231           C1   
1   ID00002       0.672619        0.02             0.375000           C2   
2   ID00003       0.841110        0.02             0.384615           C3   
3   ID00004       0.900277        0.11             0.432692           C4   
4   ID00005       0.596403        0.11             0.634615           C5   

   population_density  make segment model fuel_type  ... is_brake_assist  \
0                4990     1       A    M1       CNG  ...              No   
1               27003     1       A    M1       CNG  ...              No   
2                4076     1       A    M1       CNG  ...              No   
3               21622     1      C1    M2    Petrol  ...             Yes   
4               34738     2       A    M3    Petrol  ...              No   

  is_power_door_locks is_central_locking  is_power_steering  \
0                  No                 No                Yes   
1                  No                 No                Yes   
2                  No                 No                Yes   
3                 Yes                Yes                Yes   
4                 Yes                Yes                Yes   

  is_driver_seat_height_adjustable is_day_night_rear_view_mirror is_ecw  \
0                               No                            No     No   
1                               No                            No     No   
2                               No                            No     No   
3                              Yes                           Yes    Yes   
4                               No                           Yes    Yes   

  is_speed_alert ncap_rating is_claim  
0            Yes           0        0  
1            Yes           0        0  
2            Yes           0        0  
3            Yes           2        0  
4            Yes           2        0  

[5 rows x 44 columns]

In [5]:
df.describe()

policy_tenure    age_of_car  age_of_policyholder  population_density  \
count   58592.000000  58592.000000         58592.000000        58592.000000   
mean        0.611246      0.069424             0.469420        18826.858667   
std         0.414156      0.056721             0.122886        17660.174792   
min         0.002735      0.000000             0.288462          290.000000   
25%         0.210250      0.020000             0.365385         6112.000000   
50%         0.573792      0.060000             0.451923         8794.000000   
75%         1.039104      0.110000             0.548077        27003.000000   
max         1.396641      1.000000             1.000000        73430.000000   

               make       airbags  displacement      cylinder      gear_box  \
count  58592.000000  58592.000000  58592.000000  58592.000000  58592.000000   
mean       1.763722      3.137066   1162.355851      3.626963      5.245443   
std        1.136988      1.832641    266.304786      0.483616      0.430353   
min        1.000000      1.000000    796.000000      3.000000      5.000000   
25%        1.000000      2.000000    796.000000      3.000000      5.000000   
50%        1.000000      2.000000   1197.000000      4.000000      5.000000   
75%        3.000000      6.000000   1493.000000      4.000000      5.000000   
max        5.000000      6.000000   1498.000000      4.000000      6.000000   

       turning_radius        length         width       height  gross_weight  \
count    58592.000000  58592.000000  58592.000000  58592.00000  58592.000000   
mean         4.852893   3850.476891   1672.233667   1553.33537   1385.276813   
std          0.228061    311.457119    112.089135     79.62227    212.423085   
min          4.500000   3445.000000   1475.000000   1475.00000   1051.000000   
25%          4.600000   3445.000000   1515.000000   1475.00000   1185.000000   
50%          4.800000   3845.000000   1735.000000   1530.00000   1335.000000   
75%          5.000000   3995.000000   1755.000000   1635.00000   1510.000000   
max          5.200000   4300.000000   1811.000000   1825.00000   1720.000000   

        ncap_rating      is_claim  
count  58592.000000  58592.000000  
mean       1.759950      0.063968  
std        1.389576      0.244698  
min        0.000000      0.000000  
25%        0.000000      0.000000  
50%        2.000000      0.000000  
75%        3.000000      0.000000  
max        5.000000      1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   policy_id                         58592 non-null  object 
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  object 
 5   population_density                58592 non-null  int64  
 6   make                              58592 non-null  int64  
 7   segment                           58592 non-null  object 
 8   model                             58592 non-null  object 
 9   fuel_type                         58592 non-null  object 
 10  max_torque                        58592 non-null  object 
 11  max_power                         58592 non-null  object 
 12  engi

In [7]:
df.isnull().sum()

policy_id                           0
policy_tenure                       0
age_of_car                          0
age_of_policyholder                 0
area_cluster                        0
population_density                  0
make                                0
segment                             0
model                               0
fuel_type                           0
max_torque                          0
max_power                           0
engine_type                         0
airbags                             0
is_esc                              0
is_adjustable_steering              0
is_tpms                             0
is_parking_sensors                  0
is_parking_camera                   0
rear_brakes_type                    0
displacement                        0
cylinder                            0
transmission_type                   0
gear_box                            0
steering_type                       0
turning_radius                      0
length      

In [8]:
df.nunique()

policy_id                           58592
policy_tenure                       58592
age_of_car                             49
age_of_policyholder                    75
area_cluster                           22
population_density                     22
make                                    5
segment                                 6
model                                  11
fuel_type                               3
max_torque                              9
max_power                               9
engine_type                            11
airbags                                 3
is_esc                                  2
is_adjustable_steering                  2
is_tpms                                 2
is_parking_sensors                      2
is_parking_camera                       2
rear_brakes_type                        2
displacement                            9
cylinder                                2
transmission_type                       2
gear_box                          

### I'm feeling that few columns are contributing less to our output, so I'm dropping them.
### All binary fields with 'Yes/No' values were converted into '1/0'
### remaining category features were converted accordng to their number of categories

In [121]:
df=df.drop(['policy_id','area_cluster','population_density','segment','airbags','length','height','width','gross_weight','displacement','model'],axis=1)

In [122]:
def encoding(df):
    new={'No':0,'Yes':1}
    brake={'Drum':0,'Disc':1}
    tmsion={'Manual':0,'Automatic':1}
    st={'Power':0,'Electric':1,'Manual':2}
    fuel={'CNG':0, 'Petrol':1, 'Diesel':2}
    et={'F8D Petrol Engine':0, '1.2 L K12N Dualjet':1,'1.0 SCe':2,'1.5 L U2 CRDi':3,'1.5 Turbocharged Revotorq':4,'K Series Dual jet':5,'1.2 L K Series Engine':6,'K10C':7,'i-DTEC':8,'G12B':9,'1.5 Turbocharged Revotron':10}
    #eg={'A':0,'C1':1,'C2':2,'B2':3,'B1':4,'Utility':5}
    df['is_esc']=df['is_esc'].map(new)
    df['is_adjustable_steering']=df['is_adjustable_steering'].map(new)
    df['is_tpms']=df['is_tpms'].map(new)
    df['is_parking_sensors']=df['is_parking_sensors'].map(new)
    df['is_parking_camera']=df['is_parking_camera'].map(new)
    df['rear_brakes_type']=df['rear_brakes_type'].map(brake)
    df['transmission_type']=df['transmission_type'].map(tmsion)
    df['steering_type']=df['steering_type'].map(st)
    df['is_front_fog_lights']=df['is_front_fog_lights'].map(new)
    df['is_rear_window_wiper']=df['is_rear_window_wiper'].map(new)
    df['is_rear_window_washer']=df['is_rear_window_washer'].map(new)
    df['is_rear_window_defogger']=df['is_rear_window_defogger'].map(new)
    df['is_brake_assist']=df['is_brake_assist'].map(new)
    df['is_power_door_locks']=df['is_power_door_locks'].map(new)
    df['is_central_locking']=df['is_central_locking'].map(new)
    df['is_power_steering']=df['is_power_steering'].map(new)
    df['is_driver_seat_height_adjustable']=df['is_driver_seat_height_adjustable'].map(new)
    df['is_day_night_rear_view_mirror']=df['is_day_night_rear_view_mirror'].map(new)
    df['is_ecw']=df['is_ecw'].map(new)
    df['is_speed_alert']=df['is_speed_alert'].map(new)
    df['max_torque']=df['max_torque'].apply(lambda x: x[0:len(x)-10])
    df['max_power']=df['max_power'].apply(lambda x: x[0:len(x)-11])
    df['fuel_type']=df['fuel_type'].map(fuel)
    df['engine_type']=df['engine_type'].map(et)
    #f['segment']=df['segment'].map(seg)
    
    
    return df

In [123]:
df_update=encoding(df)
df['max_torque']=df['max_torque'].astype(float)
df['max_power']=df['max_power'].astype(float)
df_update.head()

policy_tenure  age_of_car  age_of_policyholder  make  fuel_type  \
0       0.515874        0.05             0.644231     1          0   
1       0.672619        0.02             0.375000     1          0   
2       0.841110        0.02             0.384615     1          0   
3       0.900277        0.11             0.432692     1          1   
4       0.596403        0.11             0.634615     2          1   

   max_torque  max_power  engine_type  is_esc  is_adjustable_steering  ...  \
0        60.0      40.36            0       0                       0  ...   
1        60.0      40.36            0       0                       0  ...   
2        60.0      40.36            0       0                       0  ...   
3       113.0      88.50            1       1                       1  ...   
4        91.0      67.06            2       0                       0  ...   

   is_brake_assist  is_power_door_locks  is_central_locking  \
0                0                    0                   0   
1                0                    0                   0   
2                0                    0                   0   
3                1                    1                   1   
4                0                    1                   1   

   is_power_steering  is_driver_seat_height_adjustable  \
0                  1                                 0   
1                  1                                 0   
2                  1                                 0   
3                  1                                 1   
4                  1                                 0   

   is_day_night_rear_view_mirror  is_ecw  is_speed_alert  ncap_rating  \
0                              0       0               1            0   
1                              0       0               1            0   
2                              0       0               1            0   
3                              1       1               1            2   
4                              1       1               1            2   

   is_claim  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 33 columns]

In [73]:
df_update.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 33 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   policy_tenure                     58592 non-null  float64
 1   age_of_car                        58592 non-null  float64
 2   age_of_policyholder               58592 non-null  float64
 3   make                              58592 non-null  int64  
 4   fuel_type                         58592 non-null  int64  
 5   max_torque                        58592 non-null  float64
 6   max_power                         58592 non-null  float64
 7   engine_type                       58592 non-null  int64  
 8   is_esc                            58592 non-null  int64  
 9   is_adjustable_steering            58592 non-null  int64  
 10  is_tpms                           58592 non-null  int64  
 11  is_parking_sensors                58592 non-null  int64  
 12  is_p

In [13]:
df_update.shape

(58592, 33)

In [81]:
# class_count_0,class_count_1=df_update['is_claim'].value_counts()
# class_0=df_update[df_update['is_claim']==0]
# class_1=df_update[df_update['is_claim']==1]
# print(class_0.shape)
# print(class_1.shape)

(54844, 33)
(3748, 33)


In [82]:
# class_0_under = class_0.sample(class_count_1)
# test_under = pd.concat([class_0_under, class_1], axis=0)
# print("total class of 1 and0:",test_under['is_claim'].value_counts())

total class of 1 and0: 0    3748
1    3748
Name: is_claim, dtype: int64


### We will build few models like LogisticRegression, RandomForest , XGBoost, CatBoost and will measure their performance using accuracy_score, confusion_matrix, F1 score.

In [87]:
from sklearn.metrics import accuracy_score

In [88]:
from sklearn.metrics import confusion_matrix,f1_score

In [22]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()

In [124]:
X=df_update.drop('is_claim',axis=1)
y=df_update['is_claim']

In [23]:
# X=sc.fit_transform(test_under.drop('is_claim',axis=1))
# y=test_under['is_claim']
# X

array([[ 0.05941385,  0.59499645, -1.09555086, ...,  0.59912917,
         0.0750637 ,  0.88345361],
       [-1.08129807,  0.59499645, -0.47705381, ..., -1.66908915,
         0.0750637 , -1.28828937],
       [-1.00179509, -0.31311395,  0.7599403 , ...,  0.59912917,
         0.0750637 ,  0.15953928],
       ...,
       [-1.28736994, -1.22122435, -0.86361446, ..., -1.66908915,
         0.0750637 , -1.28828937],
       [-0.97506586,  0.05013021,  0.68262817, ...,  0.59912917,
         0.0750637 ,  0.88345361],
       [-1.43800754, -0.31311395, -0.94092659, ...,  0.59912917,
         0.0750637 ,  0.88345361]])

In [27]:
from sklearn.model_selection import train_test_split

In [125]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=7)

In [126]:
X_train

policy_tenure  age_of_car  age_of_policyholder  make  fuel_type  \
48548       0.296417        0.01             0.413462     4          2   
16991       0.159730        0.00             0.384615     1          0   
42426       1.050171        0.18             0.346154     3          2   
51512       0.939314        0.01             0.528846     1          0   
1328        0.970928        0.07             0.490385     1          1   
...              ...         ...                  ...   ...        ...   
53459       0.417654        0.00             0.403846     1          0   
38467       0.137761        0.04             0.288462     1          0   
10742       1.209583        0.13             0.586538     1          1   
49689       0.220895        0.16             0.500000     1          1   
58564       0.421275        0.02             0.346154     1          0   

       max_torque  max_power  engine_type  is_esc  is_adjustable_steering  \
48548       200.0      88.77            4       0                       1   
16991        60.0      40.36            0       0                       0   
42426       250.0     113.45            3       1                       1   
51512        60.0      40.36            0       0                       0   
1328        113.0      88.50            6       1                       1   
...           ...        ...          ...     ...                     ...   
53459        60.0      40.36            0       0                       0   
38467        60.0      40.36            0       0                       0   
10742       113.0      88.50            5       0                       1   
49689       113.0      88.50            5       0                       1   
58564        60.0      40.36            0       0                       0   

       ...  is_rear_window_defogger  is_brake_assist  is_power_door_locks  \
48548  ...                        0                0                    1   
16991  ...                        0                0                    0   
42426  ...                        1                1                    1   
51512  ...                        0                0                    0   
1328   ...                        1                1                    1   
...    ...                      ...              ...                  ...   
53459  ...                        0                0                    0   
38467  ...                        0                0                    0   
10742  ...                        0                1                    1   
49689  ...                        0                1                    1   
58564  ...                        0                0                    0   

       is_central_locking  is_power_steering  \
48548                   1                  1   
16991                   0                  1   
42426                   1                  1   
51512                   0                  1   
1328                    1                  1   
...                   ...                ...   
53459                   0                  1   
38467                   0                  1   
10742                   1                  1   
49689                   1                  1   
58564                   0                  1   

       is_driver_seat_height_adjustable  is_day_night_rear_view_mirror  \
48548                                 0                              0   
16991                                 0                              0   
42426                                 1                              0   
51512                                 0                              0   
1328                                  1                              1   
...                                 ...                            ...   
53459                                 0                              0   
38467                                 0                              0   
10742                    

In [127]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(41014, 32)
(17578, 32)
(41014,)
(17578,)


### Logistic Regression 

In [86]:
from sklearn.linear_model import LogisticRegression

In [128]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [129]:
train_score=lr.predict(X_test)

In [130]:
train_score

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [131]:
accuracy_score(y_test,train_score)

0.9354875412447378

In [132]:
confusion_matrix(y_test,train_score)

array([[16444,     0],
       [ 1134,     0]], dtype=int64)

In [133]:
f1_score(y_test,train_score)

0.0

In [40]:
df_test=pd.read_csv('test_zo1G9sv.csv')

In [155]:
df_test=df_test.drop(['policy_id','area_cluster','population_density','segment','airbags','length','height','width','gross_weight','displacement','model'],axis=1)
testing=encoding(df_test)
# sc.fit(X)
# test=sc.transform(test)

NameError: name 'df_test' is not defined

In [42]:
testing.shape

(39063, 32)

In [43]:
y_pred=lr.predict(testing)

In [44]:
output=pd.DataFrame(y_pred)

In [45]:
output=output.rename(columns={0:'output'})


In [46]:
output['output'].unique()

array([0, 1], dtype=int64)

### Random Forest Classifier 

In [153]:
from sklearn.ensemble import RandomForestClassifier

In [154]:
rfc=RandomForestClassifier(n_estimators=1000)
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1000)

In [136]:
pred=rfc.predict(X_test)

In [137]:
accuracy_score(y_test,pred)

0.9280919330981909

In [138]:
confusion_matrix(y_test,pred)

array([[16297,   147],
       [ 1117,    17]], dtype=int64)

### XGBClassifier 

In [139]:
from xgboost import XGBClassifier

In [140]:
xgb=XGBClassifier(gamma=5, learning_rate=0.01, n_estimators=500, random_state=42,max_depth=3)

In [141]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=5, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.01, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=3, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=500, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=42, ...)

In [142]:
xgb_pred=xgb.predict(X_test)

In [143]:
accuracy_score(y_test,xgb_pred)

0.9354875412447378

In [144]:
confusion_matrix(y_test,xgb_pred)

array([[16444,     0],
       [ 1134,     0]], dtype=int64)

### CatBoostClassifier 

In [145]:
from catboost import CatBoostClassifier

In [146]:
categorical_features_indices = np.where((X_train.dtypes == object).values.astype(int) == 1)[0]

In [147]:
catboost_base = CatBoostClassifier(verbose=False,random_state=0, scale_pos_weight=10)
catboost_base.fit(X_train, y_train,cat_features=categorical_features_indices,eval_set=(X_test,y_test))

In [148]:
cat_pred=catboost_base.predict(X_test)

In [149]:
accuracy_score(y_test,cat_pred)

0.7942314256456935

In [150]:
confusion_matrix(y_test,cat_pred)

array([[13593,  2851],
       [  766,   368]], dtype=int64)